[project]
name = "eas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "rpi-gpio>=0.7.1 ; sys_platform == 'linux'",
    "ruff>=0.14.2",
]
